name: geemee_flutter
description: A Flutter plugin for integrating the GeeMee Android SDK, supporting OfferWall, Banner Ads, Interstitial Ads, and PlayMee User Center.
version: 0.0.2
homepage: https://github.com/jaiswal4sudeep/geemee_flutter
repository: https://github.com/jaiswal4sudeep/geemee_flutter

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sudeep.geemee_flutter
        pluginClass: GeemeeFlutterPlugin